export const INVENTORY_TEMPLATE = [
  { name: '200ML CAN', code: '020', category: 'Soft Drinks', price: 25, stock: 0, tax_type: '15%' },
  { name: '300ML CAN', code: '030', category: 'Soft Drinks', price: 28, stock: 0, tax_type: '15%' },
  { name: 'TOMATO COCKTAIL', code: '0TO', category: 'Soft Drinks', price: 30, stock: 0, tax_type: '15%' },
  { name: '500ML WATER', code: '050', category: 'Soft Drinks', price: 27, stock: 0, tax_type: '15%' },
  { name: 'APPELTISER', code: '0AP', category: 'Soft Drinks', price: 40, stock: 0, tax_type: '15%' },
  { name: 'RED BULL', code: '0RE', category: 'Energy Drinks', price: 38, stock: 0, tax_type: '15%' },
  { name: 'CASTLE LIGHT', code: '0CA', category: 'Beers', price: 34, stock: 0, tax_type: '15%' },
  { name: 'AMSTEL', code: '0AM', category: 'Beers', price: 37, stock: 0, tax_type: '15%' },
  { name: 'CORONA', code: '0CO', category: 'Beers', price: 43, stock: 0, tax_type: '15%' },
  { name: 'HEINEKEN', code: '0HE', category: 'Beers', price: 36, stock: 0, tax_type: '15%' },
  { name: 'SAVANNA', code: '0SA', category: 'Ciders', price: 37, stock: 0, tax_type: '15%' },
  { name: 'HUNTERS DRY', code: '0HU', category: 'Ciders', price: 44, stock: 0, tax_type: '15%' },
  { name: 'SMIRNOFF', code: '0SM', category: 'Spirits', price: 15, stock: 0, tax_type: '15%' },
  { name: 'RICHLIUE', code: '0RI', category: 'Brandy', price: 15, stock: 0, tax_type: '15%' },
  { name: 'KLIPDRIFT', code: '0KL', category: 'Brandy', price: 15, stock: 0, tax_type: '15%' },
  { name: 'JAMESON', code: '0JA', category: 'Whiskey', price: 26, stock: 0, tax_type: '15%' },
  { name: 'JAGGERMEISTER', code: '0JA', category: 'Shooters', price: 48, stock: 0, tax_type: '15%' },
  { name: 'TEQUILLA', code: '0TE', category: 'Shooters', price: 90, stock: 0, tax_type: '15%' },
  { name: 'GRACA BOTTLE', code: '0GR', category: 'Wines', price: 75, stock: 0, tax_type: '15%' },
  // Enhanced additions
  { name: 'JACK DANIELS', code: '0JA', category: 'Whiskey', price: 48, stock: 0, tax_type: '15%' },
  { name: 'HANNES JIM BEAM', code: '0HA', category: 'Whiskey', price: 48, stock: 0, tax_type: '15%' },
  { name: 'BLACK LABEL DRAUGHT', code: '0BL', category: 'Beers', price: 29, stock: 0, tax_type: '15%' },
  { name: 'STELLA', code: '0ST', category: 'Beers', price: 37, stock: 0, tax_type: '15%' },
  { name: 'BRUTAL FRUIT', code: '0BR', category: 'Ciders', price: 37, stock: 0, tax_type: '15%' },
  { name: 'BELGRAVIA', code: '0BE', category: 'Ciders', price: 38, stock: 0, tax_type: '15%' },
  { name: 'KWV 5 YEARS', code: '0KW', category: 'Brandy', price: 15, stock: 0, tax_type: '15%' },
  { name: 'HENNESSEY', code: '0HE', category: 'Cognac', price: 15, stock: 0, tax_type: '15%' },
  { name: 'KLIPDRIFT PREMIUM', code: '0KL', category: 'Brandy', price: 19, stock: 0, tax_type: '15%' },
  { name: 'BELLS', code: '0BE', category: 'Whiskey', price: 21, stock: 0, tax_type: '15%' },
  { name: 'JOHNNY WALKER BLACK', code: '0JO', category: 'Whiskey', price: 49, stock: 0, tax_type: '15%' },
  { name: 'STRAWBERRY LIPS', code: '0ST', category: 'Shooters', price: 18, stock: 0, tax_type: '15%' },
  { name: 'SPRINGBOKKIE', code: '0SP', category: 'Shooters', price: 25, stock: 0, tax_type: '15%' },
  { name: 'NEDERBURG CAB', code: '0NE', category: 'Wines', price: 115, stock: 0, tax_type: '15%' },
  { name: 'CASTLE LAGER', code: '0CL', category: 'Beers', price: 32, stock: 0, tax_type: '15%' },
  { name: 'HANSA PILSENER', code: '0HP', category: 'Beers', price: 30, stock: 0, tax_type: '15%' },
  { name: 'FLYING FISH LEMON', code: '0FF', category: 'Beers', price: 35, stock: 0, tax_type: '15%' },
  { name: 'SAVANNA ANGRY LEMON', code: '0AL', category: 'Ciders', price: 40, stock: 0, tax_type: '15%' },
  { name: 'BERNINI BLUSH', code: '0BB', category: 'Ciders', price: 38, stock: 0, tax_type: '15%' },
  { name: 'EXTREME SPIRIT', code: '0EX', category: 'Ciders', price: 42, stock: 0, tax_type: '15%' },
  { name: 'VICEROY BRANDY', code: '0VB', category: 'Brandy', price: 18, stock: 0, tax_type: '15%' },
  { name: 'OLOF BERGH', code: '0OB', category: 'Brandy', price: 18, stock: 0, tax_type: '15%' },
  { name: 'MAINSTAY CANE', code: '0MC', category: 'Spirits', price: 16, stock: 0, tax_type: '15%' },
  { name: 'STONEY GINGER BEER', code: '0SG', category: 'Soft Drinks', price: 28, stock: 0, tax_type: '15%' },
  { name: 'CREAM SODA', code: '0CS', category: 'Soft Drinks', price: 26, stock: 0, tax_type: '15%' },
  { name: 'SPARLETTA RASPBERRY', code: '0SR', category: 'Soft Drinks', price: 26, stock: 0, tax_type: '15%' },
  { name: 'AMARULA GINGER', code: '0AG', category: 'Shooters', price: 30, stock: 0, tax_type: '15%' },
];
